### ISSUE TITLE
Fork the source code

### ISSUE THREAD

**Issue by agilajah** [emaadmanzoor/blog#1]
Hello, there.

I found your blog is great and I am interested to use it as a base for my site. Can I fork or clone the source code?

**Comment by emaadmanzoor** [comment]
Sure! Please make sure to delete all the articles and change your name, because it'll show up as a duplicate of my website otherwise! I'm sorry it's not a ready-to-use theme at the moment, but I'm happy you found it useful!

**Comment by agilajah** [comment]
Wow, thank you very much! sure, I will. 
no problem, it is neat and great theme, though.
